### ISSUE TITLE
I can't find the .exe file

### ISSUE THREAD

**Issue by satvrnvsinvictvm** [mickboere/fanlang#2]
I've used this wonderful app once and I remember it containing one .exe to run without having to follow more complicated steps. I recently went to download it again, but found no executable. Could you tell me if it was just an oversight of mine or did you actually withdraw it?

**Comment by mickboere** [comment]
Hi! First of all thanks for the kind words, haven't actually heard of anyone using this lol so if you have any feedback be sure to let me know :)
I did not withdraw it so it must have been an oversight on your part. If you go to the [releases](https://github.com/mickboere/fanlang/releases) page you need to download the [FanLang_1.0.zip](https://github.com/mickboere/fanlang/releases/download/v1.0/FanLang_1.0.zip) file (I embedded the link for you so you don't have to look yourself), in that zip is the FanLang.exe
Good luck on your project!

**Comment by satvrnvsinvictvm** [comment]
Thank you so much.
